const base_url: string = "https://cdn.libercapital.com.br/libs/brands/assets";

export interface BrandScheme {
  code: string;
  display_name: string;
  type: string;
  icon?: string;
}

const list: readonly BrandScheme[] = [
  {
    code: "ACC",
    display_name: "Amex",
    type: "Crédito",
  }, {
    code: "AGC",
    display_name: "Agiplan",
    type: "Crédito",
    icon: `${base_url}/agibank.png`,
  }, {
    code: "AUC",
    display_name: "Aura",
    type: "Crédito",
    icon: `${base_url}/aura.png`,
  }, {
    code: "AVC",
    display_name: "Avista",
    type: "Crédito",
    icon: `${base_url}/avista.png`,
  }, {
    code: "BCC",
    display_name: "Banescard",
    type: "Crédito",
    icon: `${base_url}/banescard.png`,
  }, {
    code: "BCD",
    display_name: "Banescard",
    type: "Débito",
    icon: `${base_url}/banescard.png`,
  }, {
    code: "BNC",
    display_name: "Banese",
    type: "Crédito",
    icon: `${base_url}/banese.png`,
  }, {
    code: "BRC",
    display_name: "Brasil Card",
    type: "Crédito",
    icon: `${base_url}/brasilcard.png`,
  }, {
    code: "BRS",
    display_name: "Banrisul",
    type: "Compra",
    icon: `${base_url}/banrisul.png`,
  }, {
    code: "CBC",
    display_name: "Cabal",
    type: "Crédito",
    icon: `${base_url}/cabal.png`,
  }, {
    code: "CBD",
    display_name: "Cabal",
    type: "Débito",
    icon: `${base_url}/cabal.png`,
  }, {
    code: "CCD",
    display_name: "Calcard",
    type: "Crédito",
    icon: `${base_url}/calcard.png`,
  }, {
    code: "CSC",
    display_name: "Credi-Shop",
    type: "Crédito",
    icon: `${base_url}/credishop.png`,
  }, {
    code: "CUP",
    display_name: "CUP",
    type: "Crédito",
    icon: `${base_url}/cup.png`,
  }, {
    code: "CZC",
    display_name: "Credz",
    type: "Crédito",
    icon: `${base_url}/credz.png`,
  }, {
    code: "DAC",
    display_name: "Dacasa",
    type: "Crédito",
    icon: `${base_url}/decasa.png`,
  }, {
    code: "DBC",
    display_name: "Discover",
    type: "Crédito",
    icon: `${base_url}/discover.png`,
  }, {
    code: "DCC",
    display_name: "Diners",
    type: "Crédito",
    icon: `${base_url}/diners.png`,
  }, {
    code: "ECC",
    display_name: "Elo",
    type: "Crédito",
    icon: `${base_url}/elo.png`,
  }, {
    code: "ECD",
    display_name: "Elo Débito",
    type: "Débito",
    icon: `${base_url}/elo.png`,
  }, {
    code: "FRC",
    display_name: "Fortbrasil",
    type: "Crédito",
    icon: `${base_url}/fortbrasil.png`,
  }, {
    code: "GCC",
    display_name: "Goodcard",
    type: "Crédito",
    icon: `${base_url}/goodcard.png`,
  }, {
    code: "HCC",
    display_name: "Hipercard",
    type: "Crédito",
    icon: `${base_url}/hipercard.png`,
  }, {
    code: "HCD",
    display_name: "Hipercard",
    type: "Débito",
    icon: `${base_url}/hipercard.png`,
  }, {
    code: "JCC",
    display_name: "JCB",
    type: "Crédito",
    icon: `${base_url}/jcb.png`,
  }, {
    code: "MAC",
    display_name: "Mais",
    type: "Crédito",
    icon: `${base_url}/mais.png`,
  }, {
    code: "MCC",
    display_name: "Mastercard",
    type: "Crédito",
    icon: `${base_url}/mastercard.png`,
  }, {
    code: "MCD",
    display_name: "Mastercard",
    type: "Débito",
    icon: `${base_url}/mastercard.png`,
  }, {
    code: "MXC",
    display_name: "Maxifrota",
    type: "Crédito",
    icon: `${base_url}/maxifrota.png`,
  }, {
    code: "OCD",
    display_name: "Ourocard",
    type: "Débito",
    icon: `${base_url}/ourocard.png`,
  }, {
    code: "RCC",
    display_name: "Redesplan",
    type: "Crédito",
  }, {
    code: "SCC",
    display_name: "Sorocred",
    type: "Crédito",
    icon: `${base_url}/sorocred.png`,
  }, {
    code: "SCD",
    display_name: "Sorocred",
    type: "Débito",
    icon: `${base_url}/sorocred.png`,
  }, {
    code: "SFC",
    display_name: "Senff",
    type: "Crédito",
    icon: `${base_url}/senff.png`,
  }, {
    code: "SIC",
    display_name: "Sicred",
    type: "Compra"
  }, {
    code: "SPC",
    display_name: "Sem Parar",
    type: "Crédito",
    icon: `${base_url}/semparar.png`,
  }, {
    code: "TKC",
    display_name: "Ticketlog Pós",
    type: "Crédito",
    icon: `${base_url}/ticketlog.png`,
  }, {
    code: "VCC",
    display_name: "Visa",
    type: "Crédito",
    icon: `${base_url}/visa.png`,
  }, {
    code: "VCD",
    display_name: "Visa",
    type: "Débito",
    icon: `${base_url}/visa.png`,
  }, {
    code: "VDC",
    display_name: "Verdecard",
    type: "Crédito",
    icon: `${base_url}/verdecard.png`,
  },
]

export default list;
